#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"; IMAGE="dokku/$APP"
APP_SPECIFIC_KEY_FOLDER="$DOKKU_ROOT/.deployment-keys/$APP/.ssh"
SHARED_KEY_FOLDER="$DOKKU_ROOT/.deployment-keys/shared/.ssh"
SOURCE_ENV_PATH="$HOME/$APP/ENV"

echo "-----> Checking deploymentkeys Plugin sanity ..."
bash $( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/install

if [[ -f "$APP_SPECIFIC_KEY_FOLDER/id_rsa" ]]; then
    FINAL_SSH_FOLDER="$APP_SPECIFIC_KEY_FOLDER"
    KEYTYPE="app specific"
  else
    if [[ -f "$SHARED_KEY_FOLDER/id_rsa" ]]; then
      FINAL_SSH_FOLDER="$SHARED_KEY_FOLDER"
      KEYTYPE="shared"
    fi
fi

echo "-----> Installing $KEYTYPE SSH keys in build environment ..."

# 1. Create the .ssh folder
id=$(docker run -i -a stdin $IMAGE /bin/bash -c "mkdir -p /app/.ssh")
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null

add_file() {
  container_id=$(cat "$1" | docker run -i -a stdin $IMAGE /bin/bash -c "cat >> $2")
  test $(docker wait $container_id) -eq 0
  docker commit $container_id $IMAGE > /dev/null
}

for file in "$FINAL_SSH_FOLDER"/*; do
  add_file "$file" "/app/.ssh/$(basename $file)"
done

if [ -e "$FINAL_SSH_FOLDER/config" ]; then
  add_file "$FINAL_SSH_FOLDER/config" "/etc/ssh/ssh_config"
fi

container_id=$(docker run -i -a stdin $IMAGE /bin/bash -c "chmod -R 600 /app/.ssh && chmod 700 /app/.ssh")
test $(docker wait $container_id) -eq 0
docker commit $container_id $IMAGE > /dev/null

